apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "${LB_NAME}"
  namespace: kube-system
  annotations:
    alb.ingress.kubernetes.io/actions.default: |
      {
        "Type": "fixed-response",
        "FixedResponseConfig": {
          "ContentType": "text/plain",
          "StatusCode": "404",
          "MessageBody": ""
        }
      }
    alb.ingress.kubernetes.io/certificate-arn: ${CERT}
    alb.ingress.kubernetes.io/group.name: ${LB_NAME}
    alb.ingress.kubernetes.io/group.order: "1000"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: ${LB_NAME}
    alb.ingress.kubernetes.io/scheme: ${LB_TYPE}
    alb.ingress.kubernetes.io/tags: "env=${ENV}"
    alb.ingress.kubernetes.io/ssl-policy: ${SSL_POLICY}
    alb.ingress.kubernetes.io/actions.ssl-redirect: |
      {
        "Type": "redirect",
        "RedirectConfig": {
          "Protocol": "HTTPS",
          "Port": "443",
          "StatusCode": "HTTP_301"
        }
      }
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: default
                port:
                  name: use-annotation
