variable "cluster_name" {}
variable "cluster_endpoint" {}
variable "env" {}
variable "region" {}
variable "irsa_oidc_provider_arn" {}
variable "eks_node_role_arn" {}
variable "karpenter_version" {}
variable "worker_node_types" {}
variable "worker_node_capacity_types" {}
variable "worker_node_arch" {}
