variable "addons" {}
variable "cluster_name" {}
variable "cluster_version" {}
variable "core_node_count" {}
variable "core_node_type" {}
variable "core_node_volume_size" {}
variable "env" {}
variable "fargate" {}
variable "log_types" {}
variable "region" {}
variable "worker_node_types" {}
variable "worker_node_capacity_types" {}
variable "worker_node_arch" {}
